# Generated by Django 3.0.7 on 2021-06-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
