# Generated by Django 3.0.7 on 2021-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
